package colegio.vistas;

import colegio.dao.*;
import colegio.entidades.*;
import java.util.*;
import javax.swing.JOptionPane;

public class ManipularNotas extends javax.swing.JInternalFrame {

  public ManipularNotas() {
    initComponents();

    alumData = new AlumnoData(con);
    matData = new MateriaData(con);

    cargarDatos();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblTitulo = new javax.swing.JLabel();
    lblAlumno = new javax.swing.JLabel();
    cmboAlumnos = new javax.swing.JComboBox<>();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    btnGuardar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();

    lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    lblTitulo.setText("Carga de notas");

    lblAlumno.setText("Alumno:");

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {"1", "Matematica", "10"}
      },
      new String [] {
        "ID", "Materia", "Nota"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, true
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(jTable1);

    btnGuardar.setText("Guardar");

    btnCancelar.setText("Cancelar");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(99, 99, 99)
            .addComponent(lblAlumno)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(cmboAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(148, 148, 148)
            .addComponent(lblTitulo))
          .addGroup(layout.createSequentialGroup()
            .addGap(126, 126, 126)
            .addComponent(btnGuardar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnCancelar)))
        .addContainerGap(27, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblTitulo)
        .addGap(22, 22, 22)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(cmboAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblAlumno))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnGuardar)
          .addComponent(btnCancelar))
        .addGap(0, 136, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancelar;
  private javax.swing.JButton btnGuardar;
  private javax.swing.JComboBox<String> cmboAlumnos;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JLabel lblAlumno;
  private javax.swing.JLabel lblTitulo;
  // End of variables declaration//GEN-END:variables

  private Conexion con = new Conexion();
  private AlumnoData alumData;
  private MateriaData matData;

  private void cargarDatos() {

    ArrayList<Alumno> alumnos = alumData.obtenerAlumnos();

    alumnos.forEach(alumno -> {
      cmboAlumnos.addItem(alumno.getNombre() + " " + alumno.getApellido());
    });

    System.out.println(cmboAlumnos.getSelectedItem());

  }

}
