package colegio.vistas;

import colegio.dao.*;
import colegio.entidades.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManipularNotas extends javax.swing.JInternalFrame {

  public ManipularNotas(Conexion con) {
    initComponents();

    alumData = new AlumnoData(con);
    matData = new MateriaData(con);
    curData = new CursadaData(con);

    model = (DefaultTableModel) tbleMaterias.getModel();

    alumnos = alumData.obtenerAlumnos();

    cargarDatos();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblTitulo = new javax.swing.JLabel();
    lblAlumno = new javax.swing.JLabel();
    cmboAlumnos = new javax.swing.JComboBox<>();
    jScrollPane1 = new javax.swing.JScrollPane();
    tbleMaterias = new javax.swing.JTable();
    btnGuardar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();

    lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    lblTitulo.setText("Carga de notas");

    lblAlumno.setText("Alumno:");

    cmboAlumnos.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cmboAlumnosItemStateChanged(evt);
      }
    });
    cmboAlumnos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmboAlumnosActionPerformed(evt);
      }
    });

    tbleMaterias.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "ID", "Materia", "Nota"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, true
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tbleMaterias);

    btnGuardar.setText("Guardar");
    btnGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGuardarActionPerformed(evt);
      }
    });

    btnCancelar.setText("Cancelar");
    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(99, 99, 99)
            .addComponent(lblAlumno)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(cmboAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(148, 148, 148)
            .addComponent(lblTitulo))
          .addGroup(layout.createSequentialGroup()
            .addGap(126, 126, 126)
            .addComponent(btnGuardar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnCancelar)))
        .addContainerGap(27, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblTitulo)
        .addGap(22, 22, 22)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(cmboAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblAlumno))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnGuardar)
          .addComponent(btnCancelar))
        .addGap(0, 136, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void cmboAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboAlumnosActionPerformed

    }//GEN-LAST:event_cmboAlumnosActionPerformed

  private void cmboAlumnosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmboAlumnosItemStateChanged
    actualizarDatos();
  }//GEN-LAST:event_cmboAlumnosItemStateChanged

  private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    actualizarDatos();
  }//GEN-LAST:event_btnCancelarActionPerformed

  private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    Alumno alumnoSeleccionado = alumnos.get(cmboAlumnos.getSelectedIndex());

    for (int i = 0; i < model.getRowCount(); i++) {
      Materia mat = matData.obtenerMateria((Integer) model.getValueAt(i, 0));
      String calif = model.getValueAt(i, 2).toString();
      double nota = Double.valueOf(calif);

      curData.actualizarNota(alumnoSeleccionado, mat, nota);
    }

  }//GEN-LAST:event_btnGuardarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancelar;
  private javax.swing.JButton btnGuardar;
  private javax.swing.JComboBox<String> cmboAlumnos;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblAlumno;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JTable tbleMaterias;
  // End of variables declaration//GEN-END:variables

  private AlumnoData alumData;
  private MateriaData matData;
  private CursadaData curData;
  private ArrayList<Alumno> alumnos;
  private DefaultTableModel model;

  private void cargarDatos() {

    Collections.sort(alumnos, new Comparator<Alumno>() {
      @Override
      public int compare(Alumno t, Alumno t1) {
        return t.getApellido().compareTo(t1.getApellido());
      }
    });

    alumnos.forEach(alumno -> {
      cmboAlumnos.addItem(alumno.getApellido() + ", " + alumno.getNombre());
    });

  }

  private void actualizarDatos() {

    model.setRowCount(0);

    Alumno alumnoSeleccionado = alumnos.get(cmboAlumnos.getSelectedIndex());

    ArrayList<Cursada> cursadas = curData.obtenerCursadasDeAlumno(alumnoSeleccionado);

    cursadas.forEach(cursada -> {

      model.addRow(new Object[]{
        cursada.getMateria().getId(),
        cursada.getMateria().getNombre(),
        cursada.getNota()
      });

    });

    if (model.getRowCount() == 0) {
      btnGuardar.setEnabled(false);
    } else {
      btnGuardar.setEnabled(true);
    }

  }

}
